name: mobile_app
description: "A new Flutter project for NumberNiceIC."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.0
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^10.0.0
  google_fonts: ^6.3.3
  flutter_widget_from_html: ^0.17.1
  url_launcher: ^6.3.2
  intl: ^0.20.2
  flutter_markdown: ^0.7.7+1
  flutter_svg: ^2.2.3
  device_info_plus: ^10.1.0 # For Android version detection
  # Social Login
  google_sign_in: ^6.3.0
  flutter_facebook_auth: ^6.0.4
  flutter_line_sdk: ^2.6.2
  webview_flutter: ^4.4.2 # For Direct LINE Login
  
  # Notifications
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.4
  permission_handler: ^11.3.1
  firebase_core: ^4.3.0
  firebase_messaging: ^16.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon_source.png"
  min_sdk_android: 21 # android min sdk value

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/buddhist_days.json

